const base = '/api'

export const HOME_API: string = base + '/home'
export const CART_API: string = base + '/cart'
export const FASHION_API: string = base + '/fashions'
export const PRODUCT_API: string = base + '/products'
export const BRAND_API: string = base + '/brands'
export const AUTH_API: string = base + '/auth'
export const IMAGE_API: string = base + '/images'
export const PROFILE_API: string = base + '/images'
export const VOUCHER_API: string = base + '/vouchers'
export const PROVINCE_API: string = base + '/province'
export const PAYMENT_API: string = base + '/payments'
export const ORDER_API: string = base + '/orders'
export const ACCOUNT_API: string = base + '/account'
